// Plain metadata only - imported by both the Vue app and
// scripts/generate-screenshot-samples.mjs (Node), so no Vite asset imports
// here; the resolved image URLs live in screenshot-sample-images.ts.
export interface ScreenshotSample {
	id: string;
	label: string;
}

// The PNGs are generated by `npm run generate:screenshot-samples` from the
// mock pages in samples-src/ - no downloaded or third-party images. Their
// analysis results ship in screenshot-sample-results.json, so selecting a
// sample never hits the live API.
export const SCREENSHOT_SAMPLES: ScreenshotSample[] = [
	{ id: "login", label: "Login form" },
	{ id: "dashboard", label: "Analytics dashboard" },
	{ id: "pricing", label: "Pricing page" },
];
